### ISSUE TITLE
DocVQA Code Release

### ISSUE THREAD

**Issue by tshrjn** [mineshmathew/pyTorch_RNN_Examples#3]
Hi Minesh, 

The DocVQA Paper & the challenge is very interesting work. It's a great step in the document understanding. In the paper, you mention the code is released on the RRC portal. However, I couldn't find any. Could you please help point out where the codebase is?

Best Regards
Tushar Jain

PS: I tried reaching out to you via your email address, however, you're "over quota" & unable to receive emails.

**Comment by mineshmathew** [comment]
The baselines code using BERT will be made available in two day's time.
adding it here https://github.com/mineshmathew/DocVQA
